version: '3.7'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web-dev:
    build: 
        context: .
        target: dev
    command: ["poetry", "run", "python", "-O", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /app/resourcedb
      - type: bind
        source: /tmp
        target: /app/tmp
    env_file:
        - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1

  web:
    build: .
    command: ["python", "-O", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /app/resourcedb
      - type: bind
        source: /tmp
        target: /app/tmp
    env_file:
        - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
  resourcedb:

