# Generated by Django 4.2.3 on 2023-07-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
