# Generated by Django 4.2.3 on 2023-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_organisation_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='region',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='slug',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
