# Generated by Django 4.2.3 on 2023-07-30 09:53

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.now),
            preserve_default=False,
        ),
    ]
