# Generated by Django 4.2.3 on 2023-07-31 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0005_event_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
