# Generated by Django 4.2.3 on 2023-07-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_organisation_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='friends',
            new_name='users',
        ),
    ]
