# Generated by Django 4.2.5 on 2023-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_remove_organisation_users_organisation_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticketed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
