# Generated by Django 4.2.5 on 2023-09-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_event_ticketed_event_tickets_event_tickets_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='logo',
        ),
    ]
