# Generated by Django 4.2.5 on 2023-09-17 13:18

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_remove_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=timedelta),
            preserve_default=False,
        ),
    ]
