# Generated by Django 4.2.8 on 2024-01-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_contact_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.organisation'),
        ),
    ]
