# Generated by Django 4.2.9 on 2024-01-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='cron',
            field=models.CharField(default='* * * * *', max_length=255),
        ),
    ]
