# Generated by Django 4.2.9 on 2024-01-31 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_alter_scheduler_cron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='cron',
            field=models.CharField(default='* * * * *', max_length=64),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='info.event'),
        ),
    ]
