# Generated by Django 4.2.9 on 2024-01-31 22:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_alter_scheduler_cron_alter_scheduler_event'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('scheduled', django.db.models.manager.Manager()),
            ],
        ),
    ]
