# Generated by Django 4.2.9 on 2024-02-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_alter_event_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_purchased',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='schedules',
            field=models.ManyToManyField(related_name='events', to='info.scheduler'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
