# Generated by Django 4.2.9 on 2024-02-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_event_managers_remove_event_tickets_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('organisation', 'name', 'start_date_time', 'location')},
        ),
    ]
