# Generated by Django 4.2.9 on 2024-02-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='events', to='info.scheduler'),
        ),
    ]
