# Generated by Django 4.2.9 on 2024-02-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_alter_event_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.organisation'),
        ),
    ]
