# Generated by Django 4.2.9 on 2024-02-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_location_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='info.organisation'),
        ),
    ]
