# Generated by Django 4.2.9 on 2024-02-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_alter_location_organisation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('start_date_time', 'location')},
        ),
    ]
