# Generated by Django 4.2.10 on 2024-03-09 20:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_rename_name_contact_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
