# Generated by Django 4.2.10 on 2024-03-09 20:06

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_organisation_phone_number_alter_organisation_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31),
        ),
    ]
