# Generated by Django 4.2.11 on 2024-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0036_event_hide"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
