# Generated by Django 4.2.13 on 2024-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0039_schedule_organisation_enable_scheduler"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="label",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="rrule",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
