# Generated by Django 4.2.13 on 2024-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0040_icalschedule_delete_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="icalschedule",
            options={
                "verbose_name": "iCalSchedule",
                "verbose_name_plural": "iCalSchedules",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="ical_rrules",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="info.icalschedule"
            ),
        ),
    ]
