# Generated by Django 4.2.13 on 2024-07-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0041_alter_icalschedule_options_event_ical_rrules"),
    ]

    operations = [
        migrations.AddField(
            model_name="icalschedule",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="info.organisation",
            ),
            preserve_default=False,
        ),
    ]
